export const rows = [
  {
    description: "APPLE INC",
    figi: "BBG000B9XRY4",
    mic: "XNAS",
    symbol: "AAPL",
  },
  {
    description: "MICROSOFT CORP",
    figi: "BBG000BPH459",
    mic: "XNAS",
    symbol: "MSFT",
  },
  {
    description: "ALPHABET INC-CL C",
    figi: "BBG009S3NB30",
    mic: "XNAS",
    symbol: "GOOG",
  },
  {
    description: "AMAZON.COM INC",
    figi: "BBG000BVPV84",
    mic: "XNAS",
    symbol: "AMZN",
  },
  {
    description: "BERKSHIRE HATHAWAY INC-CL A",
    figi: "BBG000DWCFL4",
    mic: "XNYS",
    symbol: "BRK.A",
  },
  {
    description: "TESLA INC",
    figi: "BBG000N9MNX3",
    mic: "XNAS",
    symbol: "TSLA",
  },
  {
    description: "UNITEDHEALTH GROUP INC",
    figi: "BBG000CH5208",
    mic: "XNYS",
    symbol: "UNH",
  },
  {
    description: "JOHNSON & JOHNSON",
    figi: "BBG000BMHYD1",
    mic: "XNYS",
    symbol: "JNJ",
  },
  {
    description: "EXXON MOBIL CORP",
    figi: "BBG000GZQ728",
    mic: "XNYS",
    symbol: "XOM",
  },
  {
    description: "VISA INC-CLASS A SHARES",
    figi: "BBG000PSKYX7",
    mic: "XNYS",
    symbol: "V",
  },
  {
    description: "NVIDIA CORP",
    figi: "BBG000BBJQV0",
    mic: "XNAS",
    symbol: "NVDA",
  },
  {
    description: "WESTMOUNTAIN GOLD INC",
    figi: "BBG000BTCB69",
    mic: "OOTC",
    symbol: "WMTN",
  },
  {
    description: "JPMORGAN CHASE & CO",
    figi: "BBG00N2WDHD0",
    mic: "XNYS",
    symbol: "JPM.PRC",
  },
  {
    description: "PROCTER & GAMBLE CO/THE",
    figi: "BBG000BR2TH3",
    mic: "XNYS",
    symbol: "PG",
  },
  {
    description: "ELI LILLY & CO",
    figi: "BBG000BNBDC2",
    mic: "XNYS",
    symbol: "LLY",
  },
  {
    description: "CHEVRON CORP",
    figi: "BBG000K4ND22",
    mic: "XNYS",
    symbol: "CVX",
  },
  {
    description: "MASTERCARD INC - A",
    figi: "BBG000F1ZSQ2",
    mic: "XNYS",
    symbol: "MA",
  },
  {
    description: "HOME DEPOT INC",
    figi: "BBG000BKZB36",
    mic: "XNYS",
    symbol: "HD",
  },
  {
    description: "META PLATFORMS INC-CLASS A",
    figi: "BBG000MM2P62",
    mic: "XNAS",
    symbol: "FB",
  },
  {
    description: "BANK OF AMERICA CORP",
    figi: "BBG000BCTLF6",
    mic: "XNYS",
    symbol: "BAC",
  },
  {
    description: "ABBVIE INC",
    figi: "BBG0025Y4RY4",
    mic: "XNYS",
    symbol: "ABBV",
  },
  {
    description: "PFIZER INC",
    figi: "BBG000BR2B91",
    mic: "XNYS",
    symbol: "PFE",
  },
  {
    description: "MERCK & CO. INC.",
    figi: "BBG000BPD168",
    mic: "XNYS",
    symbol: "MRK",
  },
  {
    description: "COCA-COLA CO/THE",
    figi: "BBG000BMX289",
    mic: "XNYS",
    symbol: "KO",
  },
  {
    description: "PEPSICO INC",
    figi: "BBG000DH7JK6",
    mic: "XNAS",
    symbol: "PEP",
  },
  {
    description: "BROADCOM INC",
    figi: "BBG00KHY5S69",
    mic: "XNAS",
    symbol: "AVGO",
  },
  {
    description: "ORACLE CORP",
    figi: "BBG000BQLTW7",
    mic: "XNYS",
    symbol: "ORCL",
  },
  {
    description: "THERMO FISHER SCIENTIFIC INC",
    figi: "BBG000BVDLH9",
    mic: "XNYS",
    symbol: "TMO",
  },
  {
    description: "COSTCO WHOLESALE CORP",
    figi: "BBG000F6H8W8",
    mic: "XNAS",
    symbol: "COST",
  },
  {
    description: "CISCO SYSTEMS INC",
    figi: "BBG000C3J3C9",
    mic: "XNAS",
    symbol: "CSCO",
  },
  {
    description: "MCDONALD'S CORP",
    figi: "BBG000BNSZP1",
    mic: "XNYS",
    symbol: "MCD",
  },
  {
    description: "DANAHER CORP",
    figi: "BBG000BH3JF8",
    mic: "XNYS",
    symbol: "DHR",
  },
  {
    description: "ACCENTURE PLC-CL A",
    figi: "BBG000D9D830",
    mic: "XNYS",
    symbol: "ACN",
  },
  {
    description: "T-MOBILE US INC",
    figi: "BBG000NDV1D4",
    mic: "XNAS",
    symbol: "TMUS",
  },
  {
    description: "ABBOTT LABORATORIES",
    figi: "BBG000B9ZXB4",
    mic: "XNYS",
    symbol: "ABT",
  },
  {
    description: "WALT DISNEY CO/THE",
    figi: "BBG000BH4R78",
    mic: "XNYS",
    symbol: "DIS",
  },
  {
    description: "NIKE INC -CL B",
    figi: "BBG000C5HS04",
    mic: "XNYS",
    symbol: "NKE",
  },
  {
    description: "WELLS FARGO & CO",
    figi: "BBG000BWQFY7",
    mic: "XNYS",
    symbol: "WFC",
  },
  {
    description: "BRISTOL-MYERS SQUIBB CO",
    figi: "BBG000DQLV23",
    mic: "XNYS",
    symbol: "BMY",
  },
  {
    description: "NEXTERA ENERGY INC",
    figi: "BBG000BJSBJ0",
    mic: "XNYS",
    symbol: "NEE",
  },
  {
    description: "LINDE PLC",
    figi: "BBG00GVR8YQ9",
    mic: "XNYS",
    symbol: "LIN",
  },
  {
    description: "UNITED PARCEL SERVICE-CL B",
    figi: "BBG000L9CV04",
    mic: "XNYS",
    symbol: "UPS",
  },
  {
    description: "PHILIP MORRIS INTERNATIONAL",
    figi: "BBG000J2XL74",
    mic: "XNYS",
    symbol: "PM",
  },
  {
    description: "TEXAS INSTRUMENTS INC",
    figi: "BBG000BVV7G1",
    mic: "XNAS",
    symbol: "TXN",
  },
  {
    description: "VERIZON COMMUNICATIONS INC",
    figi: "BBG000HS77T5",
    mic: "XNYS",
    symbol: "VZ",
  },
  {
    description: "ADOBE INC",
    figi: "BBG000BB5006",
    mic: "XNAS",
    symbol: "ADBE",
  },
  {
    description: "MORGAN STANLEY",
    figi: "BBG000BLZRJ2",
    mic: "XNYS",
    symbol: "MS",
  },
  {
    description: "COMCAST CORP-CLASS A",
    figi: "BBG000BFT2L4",
    mic: "XNAS",
    symbol: "CMCSA",
  },
  {
    description: "SCHWAB (CHARLES) CORP",
    figi: "BBG000BSLZY7",
    mic: "XNYS",
    symbol: "SCHW",
  },
  {
    description: "AMGEN INC",
    figi: "BBG000BBS2Y0",
    mic: "XNAS",
    symbol: "AMGN",
  },
  {
    description: "CONOCOPHILLIPS",
    figi: "BBG000BQQH30",
    mic: "XNYS",
    symbol: "COP",
  },
  {
    description: "RAYTHEON TECHNOLOGIES CORP",
    figi: "BBG000BW8S60",
    mic: "XNYS",
    symbol: "RTX",
  },
  {
    description: "HONEYWELL INTERNATIONAL INC",
    figi: "BBG000H556T9",
    mic: "XNAS",
    symbol: "HON",
  },
  {
    description: "SALESFORCE INC",
    figi: "BBG000BN2DC2",
    mic: "XNYS",
    symbol: "CRM",
  },
  {
    description: "NETFLIX INC",
    figi: "BBG000CL9VN6",
    mic: "XNAS",
    symbol: "NFLX",
  },
  {
    description: "QUALCOMM INC",
    figi: "BBG000CGC1X8",
    mic: "XNAS",
    symbol: "QCOM",
  },
  {
    description: "AT&T INC",
    figi: "BBG000BSJK37",
    mic: "XNYS",
    symbol: "T",
  },
  {
    description: "CVS HEALTH CORP",
    figi: "BBG000BGRY34",
    mic: "XNYS",
    symbol: "CVS",
  },
  {
    description: "DEERE & CO",
    figi: "BBG000BH1NH9",
    mic: "XNYS",
    symbol: "DE",
  },
  {
    description: "INTL BUSINESS MACHINES CORP",
    figi: "BBG000BLNNH6",
    mic: "XNYS",
    symbol: "IBM",
  },
];
